name       : python-keras
version    : '2.8'
release    : 2
source     :
    - https://files.pythonhosted.org/packages/4f/2f/eb9391bdcba2693cc8396f244bd3b4512bcd1123c2ea06f4dfcf50dc5ce9/keras-2.8.0-py2.py3-none-any.whl : 744d39dc6577dcd80ff4a4d41549e92b77d6a17e0edd58a431d30656e29bc94e
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow Keras
description: |
    TensorFlow Keras is an implementation of the Keras API that uses TensorFlow as a backend.
install    : |
    python3 -m pip install --root=%installroot% --no-deps --disable-pip-version-check --verbose --ignore-installed --no-warn-script-location --no-index --no-cache-dir $sources/*.whl
